// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugtwljwpoldlvvfdiear.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVndHdsandwb2xkbHZ2ZmRpZWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NzAwNzQsImV4cCI6MjA1OTE0NjA3NH0.FqEwqXDksg9Qfh1p33HT6Tu7Nk-Z-7LhO-JVGc5jcgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);